### ISSUE TITLE
Redirect to domains that don't start with "www."

### ISSUE THREAD

**Issue by tzimon** [sblask/webextension-skip-redirect#109]
To me it seems like the addon only works if the contained link (the one you are redirected to) looks like this: `www.example.*`,  but not if the link is e.g. `m.example.*` ore anything else. Can this be fixed?

**Comment by sblask** [comment]
There are many rules, I think `www.` is one of the special ones. In general, the addon looks for `http://` or `https://` which are safe signs for a URL. If neither can be found, `www.` is another sign for a (incomplete) URL. I can't search for m.example.com because then I'd need to look for all kinds of letter-dot-combinations...

**Comment by Sopor-** [comment]
But isn't `m.example.com` something you use for mobile phones? So it is only the letter `m` you need to look for?

**Comment by sblask** [comment]
Sure, but I don't want to add yet another special case.
