### ISSUE TITLE
whitelist and blacklist

### ISSUE THREAD

**Issue by crssi** [sblask/webextension-skip-redirect#165]
Due to latest situation did you consider to make a change to the naming whitelist and blacklist as allowlist and denylist accordingly?

Cheers

**Comment by sblask** [comment]
You mean black lives matter? I think changing the names is a bit silly because they have nothing to do with skin colour. However, as some people got confused in the past I was thinking about changing the name or just not naming the lists at all for a while. Just never got around doing it. With that in mind I would also not like allowlist/denylist. How about skiplist for what is now whitelist and noskiplist for blacklist? Any thoughts on adding dashes/whitespaces? As in `no-skip-list` vs `no-skip list` vs `no skip list`.

**Comment by crssi** [comment]
Yes, that is I have meant. I know it has nothing to do with it. It has everything to do with the day and night, but people finds all kinds of excuses that servers their purpose.

I have mentioned it just because your web extension is really great and really don't want it to get on some hate list because of nonsense and someone does not understand.

Anyway... this was not an issue or a request... just kind of a brainstorming.
Thank you for your extension and cheers ❤️

**Comment by sblask** [comment]
I think I will change the names, just not to be politically correct...
