### ISSUE TITLE
please publish release notes for about:addons

### ISSUE THREAD

**Issue by atomGit** [sblask/webextension-skip-redirect#180]
how does one know what changes were made? what features were added/removed? etc.

users cannot be expected to go to github and read the commits which they may not understand anyway

Firefox includes a release notes tab in the add-ons about page - **please** consider utilizing it

**Comment by ImSpecial** [comment]
This. It's annoying for us users to have to constantly guess, like the regression I reported last time, it would have been much simpler for me if I knew what was being changed. (you said you added a delay.)

**Comment by sblask** [comment]
You are on Github, so I assume you know how it works? If you are super curious you can just go to tags/releases and read the git changelog.

When I upload a package for Firefox, it looks like there is supposed to be a field for release notes, but there isn't. So I have no idea how to populate what you see on the about page. Firefox/Chrome developer support is really terrible, there is no way to automate READMEs and changelogs and I don't have the time to do manual stuff.

Also, how would you know when to check the changelog? I will never start adding update notifications. You saw a change in the UI? Then that's the change. It should all be self explanatory. If you find a bug, you can report it and maybe I have time to fix it. It's not like there is a lot of activity going on here, if you report a bug I will most likely know where it's coming from. 

@ImSpecial  it is highly unlikely that the information about the delay would have made into a changelog, because it's not a feature. Not sure why you have to constantly guess anything.

**Comment by atomGit** [comment]
> You are on Github, so I assume you know how it works?

you miss the point - no one should have to come here to get an overview of what changed

> When I upload a package for Firefox, it looks like there is supposed to be a field for release notes, but there isn't.

not an add-on developer so i'm not sure, but i think you add release notes from the add-on page at AMO

> Also, how would you know when to check the changelog?

when the add-on is updated of course - people that want to check it can do so right from about:addons, as i mentioned, rather than wasting time having to hunt down the site where the code is and more time sifting through commits

>  I will never start adding update notifications.

there's no need to - people that **want** to see what changed can do so from about:addons

for example, for Commits on Aug 24, 2020, you merged a PR - ok, so what happened? was something added? removed? fixed? were you approached by a marketing company to monetize the add-on? <-- that's happened with many add-ons and it's a serious privacy issue

that commit was a simple one, but the point is, this info should be available from Firefox like virtually every other developer is doing

i appreciate your work - the ext. works well and seems well thought out - i like that i have the option of being notified of redirects and all of it, and i'm (we're) not asking that you document every little itsy-bitsy thing - just please consider providing a brief, human readable description of the changes

**Comment by sblask** [comment]
I just re-checked, not way to add release notes in the developer dashboard.

I am not using Firefox anymore, so I wouldn't know who "virtually every other developer" is, but I never checked any changelog for extensions. What's the point as long as it works? And I wouldn't know when because I don't get notified about updates and I find notifications popping up like some extensions have very annoying.

I have been approached about monetisation, but rest assured, I will never add something like that. But I would expect people doing it to hide the fact and not add it to the changelog anyway.

I kind of expect this extension to go back into hibernation again now, I only added a few things that I wanted or other people raised issues about and I had time to work on them. Now there is nothing left on my todo list. The only thing happening will probably be translation fixes.
