### ISSUE TITLE
archive.org

### ISSUE THREAD

**Issue by scoid** [sblask/webextension-skip-redirect#312]
### New Issue Checklist (tick off like this: `[x]`)

- [ ] I checked existing issues (open and closed) for possible duplicates
- [x] I can reproduce the problem on the latest stable version (not nightly!)
- [x] If you have a problem with a specific website: adding the domain to your no-skip-urls-list does not solve the problem
- [ ] The issue is not about adding entries to the default no-skip-urls-list

### What is your browser?

- [x] Firefox
- [ ] Chrome

### What is your operating system?

- [x] Linux
- [ ] Mac
- [ ] Windows

**Comment by scoid** [comment]
Your extensions works fine. :-) Recently I tried to search for an URL on https://archive.org/ , then your extension boomeranged me back to the original URL.

**Comment by erAck** [comment]
Any `http://web.archive.org/` URL like `http://web.archive.org/web/20230117161921/https://www.wikipedia.org/` is redirected to the source page i.e. `https://www.wikipedia.org/`, adding only `http://web.archive.org/` to No-skip-urls-list does not help, maybe because Firefox is set to always use https (but does not do that for web.archive.org). Adding _both_
`https://web.archive.org/`
`http://web.archive.org/`
helps. Adding only `https://web.archive.org/` though does not help for `http://web.archive.org/...` either, but adding only
`/web.archive.org/`
does help in both http and https cases (but maybe also makes anything slip through that only _contains_ it not as host.domain part?)

IMHO *://web.archive.org/ should never be redirected.

**Comment by doomikus** [comment]
I'm also having the same issue with Firefox and Arch Linux.

`https://*.archive.org/*`

Should meet Mozilla's standard of matching including `*.` requirement in the host portion and a wildcard path

**Comment by shelacek** [comment]
Also `https://search.google.com/search-console/links?resource_id=<uri>` is redirected, although in this case it is a feature rather than a bug :wink:. Anyway, some sort of blacklist of sites where _Skip Redirect_ would be disabled will be great.

**Comment by sblask** [comment]
This is what the no skip lists are for, but I am not maintaining this for the whole Web.
