### ISSUE TITLE
One click turning on/off

### ISSUE THREAD

**Issue by sanyarnd** [sblask/webextension-skip-redirect#48]
Not long ago you've updated add-on, I like the update, but one feature presented in the old version is forgotten: MMB turn on/off. Usually add-on works fine, but some sites have very complex URL redirection add-on cannot handle, so I had to temporally disable it.
New version has lots of new functionality, but it's missing one I've described above: quick way to turn it off and back on. It's a pain to open menu each time I want to turn it on and off.
Can you add this functionality in the next release?

Cheers, 
Alexander.

**Comment by sblask** [comment]
See #36

**Comment by sanyarnd** [comment]
It proposes to use LMB to turn on/off. Why not MMB? It's not currently binded.

**Comment by crssi** [comment]
This "problem" bothers me too.
It would be better to bind LMB to on/off toggle and the RMB to open options, then under the option could be button for "Copy last skipped URL", which is fine, but rarely used.
That is just my humble opinion.

Cheers

**Comment by sblask** [comment]
I assume MMB stands for middle mouse button? There is no API make use of it. There is click (left click) and context menu. As to why there is no on/off: there is no simple "on" anymore, there are two modes and I don't want to split modes and on/off into two preferences.

**Comment by vertigo220** [comment]
Personally, I think splitting them would be better. I would much prefer LMB to toggle the addon on/off and RMB to have the option to open the menu, since that's not likely to be needed as often, and if you need to copy the last skip to put it in one of the lists, you're going to need to get into the menu anyways in order to actually enter it, so instead of right-click, copy last skipped, left-click, paste into the box, it could be right-click, open menu, then have a button for each list to paste the last skipped right into the list for that button.

And as for splitting on/off and modes, it doesn't make sense that the mode would need to be changed often anyways. Users are going to run it one way or the other. So that should be its own setting, and on/off should be its own thing. I actually think having them all together like they are just makes it more confusing for less techy users. For example, I plan to include this addon on my parents' setups, and they would be much more able to handle simply clicking the icon to toggle on/off vs opening a confusing (for them) pop-up, finding the off option, then selecting the correct option when re-enabling it.

**Comment by sblask** [comment]
I would strongly advise against putting it on your parent's computer. They will not understand what's going on...

**Comment by vertigo220** [comment]
Well, my dad would, but I'd still rather not make it any harder than it needs to be. He could figure out any issues, but I'd still prefer keeping it as simple as possible. It's not just about being able to use it, but making it as easy to use (and more difficult to screw up) as possible. Anyways, I was just giving my thoughts and personal preference, as I'd still like it to be that way myself.
