### ISSUE TITLE
Feature request: Clean URL when copying to clipboard

### ISSUE THREAD

**Issue by PaperbackSpine** [sblask/webextension-skip-redirect#62]
I used the Google Privacy addon, but with the latest Firefox version it stopped working so this addon has become the replacement. It is superior too, because it supports more domains beyond google.

A feature I miss is that the URL isn't cleaned when copying to clipboard. I need to actually visit the page first, to obtain the clean URL, and then I can copy that to clipboard. With the old Google Privacy addon, I could right click a search result, choose "copy URL to clipboard" and directly have a clean URL for sharing on dicussion forums etc.

Would it be possible to implement this feature?

**Comment by PaperbackSpine** [comment]
Also consider use-case where facebook considers the copying of a URL to be the same as a click, while hiding this from the user by putting the clean URL on the clipboard and, on mouseover, in the status bar.

**Comment by NamelessVoice** [comment]
Agreed.

Would it be possible to replace the URL in the link on mouseover instead of when it's clicked, so that the link preview also isn't garbled?

**Comment by sblask** [comment]
A lot of things are possible, but the only thing I might consider is a separate entry in the context menu to copy a cleaned link. Not sure what your issue with Facebook is.

**Comment by PaperbackSpine** [comment]
@sblask That would work :)

With FB I mean that FB already cleans the link for me when I copy to clipboard. Shows clean link on mouseover. But when I right-click, it sends tracking data to FB servers anyway. Not sure how to block this.

**Comment by hyperfekt** [comment]
I had a similar wish and created [a fork](https://addons.mozilla.org/en-US/firefox/addon/remove-redirect/) that provides this capability by rewriting href attributes instead of HTTP requests. I hope Sebastian doesn't mind.

**Comment by sblask** [comment]
I don't mind, but I don't think it will work so well? I still get websites with weird redirects where I need to disable skipping and click again. With your extension I will have to reload the website as well before clicking? The Javascript limitations are a problem as well. Unfortunately there are more and more websites that don't use hrefs properly :-(

**Comment by hyperfekt** [comment]
Indeed, it is definitely not a complete replacement, the features rather complement each other rather than overlap.
Maybe both techniques at the same time is the ideal solution - I will take a look at how to do that elegantly.
Could you give an example of a website where Skip Redirect works and Remove Redirect breaks links?

**Comment by sblask** [comment]
I didn't mean it like this. The whole concept of extracting URLs from another URL is flawed. It can work or not. And in case it doesn't there must be a good way to just open the original URL without any modifications. I have plans to improve it for Skip Redirect, just not much time. If I understand it right you won't even know what's going on if something is broken in Remove Redirect, because the original URL is not visible at all? And you don't get a notification either? So stuff just breaks and the user has no idea where it's coming form.

**Comment by hyperfekt** [comment]
Ah, yes. Indeed, that's a critical limitation that constrains the intended userbase to power users who will actually notice and troubleshoot if something doesn't work as expected. There might be a way to patch this by maintaining a sort of per-link history, but I'm not sure if those users wouldn't generally be better served by Skip Redirect, which is inherently less fragile.

**Comment by sblask** [comment]
I don't think this will happen from my side, so I'll just close the issue.
