### ISSUE TITLE
Wrong redirect

### ISSUE THREAD

**Issue by StealthBlackOxide** [sblask/webextension-skip-redirect#71]
https://outgoing.prod.mozaws.net/v1/9b92b9910062e5ab748313bf09ded6984cabce25a1ff2af6eb32f5f5fc3c9787/http%3A//www.phoronix.com/scan.php%3Fpage=news_item&px=Ioquake3-Auto-Updater&utm_source=feedburner&utm_medium=feed&utm_campaign=Feed%253A%2BPhoronix%2B%28Phoronix%29

leads to News overview page instead of Article about "Ioquake3 Auto Updater"

**Comment by sblask** [comment]
`&` should be escaped too, like this, it appears like the URL end right before the first `&`.

**Comment by hyperfekt** [comment]
I have seen a couple of redirecting URLs that do not escape the & character as well, maybe it would be worth to consider it part of a target URL if there isn't any ? in front of the target URL, since then it can't reasonably be a GET parameter for the redirecting page.

**Comment by sblask** [comment]
That's an option, but I am trying to keep the logic sane. If nothing were encoded in the phoronix URL, the whole URL would be picked. There is no reason (that I can see) why anything is encoded in the URL at all. So as I don't understand the logic, I won't add another special case. It's true that without a `?` it can't be a get parameter, but people can do in their URLs whatever they want so that's not a good argument.

**Comment by crssi** [comment]
The internet is full of broken stuff.
In this case the "bug" on some pages to not escape the chars might be also intentional to make addons like this one to not work as intended.
It would be very nice if you can make this work even when URL does not meet the standards to escape chars.
@sblask could you maybe reconsider and implement those cases anyway?

Thank you and cheers
